// Generated by https://quicktype.io

export interface IUsuarioCreate {
  nombre: string;
  apellidoPaterno: string;
  apellidoMaterno: string;
  email: string;
  contrasena: string;
  status: number;
  rol: Rol;
}

export interface Rol {
  id: number;
}
