// Generated by https://quicktype.io

export interface IUsuarioRead {
  id: string;
  nombre: string;
  apellidoPaterno: string;
  apellidoMaterno: string;
  email: string;
  status: number;
  rol: IUsuarioRol;
}

export interface IUsuarioRol {
  id: number;
  nombre: string;
  descripcion?: string;
}

export interface IFullUsuarioRead extends IUsuarioRead{
  contrasena: string;
}
