// Generated by https://quicktype.io

import { IMarcaRead } from "src/app/marcas/models/interface";
import { ISkuRead } from "src/app/skus/models/interface";
import { ITipoEnvaseRead } from "src/app/tipo-envase/models/interface";
import { IUbicacionRead } from "src/app/ubicaciones/models/interface";
import { IUnidadMedidaRead } from "src/app/unidades-medida/models/interface";

export interface IReactivoRead {
  id: string;
  nombre: string;
  desripcion?: string;
  stock: number;
  cantidad: number;
  estadoFisico: string;
  clasificacion: string;
  fechaIngreso: string;
  hojaSeguridad: boolean;
  status: number;
  unidadMedida: IUnidadMedidaRead;
  marca: IMarcaRead;
  tipoEnvase: ITipoEnvaseRead;
  ubicacion: IUbicacionRead;
  skus: ISkuRead[];
}
