// Generated by https://quicktype.io

import { ISkuSmCreate } from "src/app/skus/models/interface";

export interface IReactivoCreate {
  nombre: string;
  desripcion?: string;
  stock: number;
  cantidad: number;
  estadoFisico: string;
  clasificacion: string;
  fechaIngreso: string;
  hojaSeguridad: boolean;
  status: number;
  unidadMedida: IReactivoRelationStringId;
  marca: IReactivoRelationStringId;
  tipoEnvase: IReactivoRelationNumberId;
  ubicacion: IReactivoRelationStringId;
  skus: ISkuSmCreate[];
}

export interface IReactivoRelationStringId {
    id: string;
}

export interface IReactivoRelationNumberId {
    id: number;
}